Algoritmo "AP1_12"
// Disciplina  :  Algortimos e Programação
// Professor   : Luciano Blomberg
// Descrição   : Números de ímpares
// Autor(a)    : Yan Braga da Silva
// Data atual  : 24/04/2023
Var
   i,j:inteiro


Inicio
   para i de 100 ate 200  faca
      escreva (i)
      se i=100 entao
         j<-i
      senao
         j<-j+i
      fimse
   fimpara
   escreva ("O somatório dos valores é: ", j)


Fimalgoritmo