Algoritmo "AP1_2"
// Disciplina  :  Algortimos e Programação
// Professor   : Luciano Blomberg
// Descrição   : X e Y são informados e em seguida seus valores são trocados
// Autor(a)    : Yan Braga da Silva
// Data atual  : 24/04/2023
Var
   x,y,z:inteiro


Inicio
   escreval ("Digite o valor de X, e em seguida Y")
   leia (x,y)
   z<-x
   x<-y
   y<-z
   escreva ("O valor de X é: ",x," e o valor de Y é: ",y)


Fimalgoritmo