Algoritmo "AP1_1"
// Disciplina  :  Algortimos e Programação
// Professor   : Luciano Blomberg
// Descrição   : Depois de dito o salário mínimo, é calculado qual o salário de uma pessoa
// Autor(a)    : Yan Braga da Silva
// Data atual  : 24/04/2023
Var
   salMin, sal:real


Inicio
   escreval ("Escreva o valor atual do salário mínimo, e em seguida um salário real: ")
   leia (salMin, sal)
   escreva ("O salário escrito corresponde a ", sal/salMin," salários mínimo(s)." )


Fimalgoritmo